### PR TITLE
Add 'parallel' option, that runs analysis of files in parallel

### PR DESCRIPTION
**Pull request by define-null**
Add 'parallel' option, that runs analysis of files in parallel
with max parallel number of processes, specified by the option.
Value 'auto' could be used to specify number equal to amount
of scheduler threads, available to emulator.

### CODE REVIEW

**Comment by define-null** [comment]
Related to https://github.com/inaka/elvis_core/pull/107

**Comment by define-null** [comment]
Hmm.. I renamed get_file/1 to get_path/1 in the elvis_results, to indicate that only file path is included in the result, as the rest of the file content is dropped. But as soon as version 0.4.0 is provided it's not the case and xref fails. 

Pls let me know what you think @elbrujohalcon

**Comment by define-null** [comment]
@elbrujohalcon Maybe you could tag elvis_core, so that I could update this PR, to reflect parallel feature?

**Comment by elbrujohalcon** [comment]
@igaray is on it! :)

**Comment by define-null** [comment]
@igaray just kind reminder

**Comment by igaray** [comment]
Thanks for the reminder, I'll get to it by EOD.

**Comment by define-null** [comment]
Noticed that `-p` option is already defined for the code-path, so fixed that. Please let me know which version do you gonna set for the elvis_core (I guess it's gonna be 5.0.0 ?).

Do you need any help with preparing release for hem.px ? Looking forward to merge this feature =)

**Comment by define-null** [comment]
@igaray just a kind reminder

**Comment by igaray** [comment]
@define-null Sorry for the delay, elvis_core has a new release 0.4.2 published on hex.pm

**Comment by define-null** [comment]
@elbrujohalcon  pls have a look once again, and let me know what you think =)

**Comment by define-null** [comment]
@elbrujohalcon Shall we merge this PR maybe?

**Comment by igaray** [comment]
LGTM, merge away

**Comment by elbrujohalcon** [comment]
@igaray merged, please bump the version and generate a release. :)

**Comment by define-null** [comment]
Great, thanks!

**Pull request merged**
